aws:
  s3:
    credentials:
      accessKey: ${{secrets.AWS_S3_ACCESS_KEY}}
      secretKey: ${{secrets.AWS_S3_SECRET_KEY}}
      region: ${{secrets.AWS_S3_REGION}}
    bucket: ${{secrets.AWS_S3_BUCKET}}