spring:
  application:
    name: ImageServer
  profiles:
    default: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mustache:
    layout: default